#!/usr/bin/env python
# coding: utf-8

# In[102]:


#传入/不传入参数生产文件夹，不传入参数，自动生产文件夹
import os,argparse
import datetime

#全局变量
now_day=datetime.datetime.now().strftime('%Y%m%d')
now_pwd=os.getcwd()
base_dir=os.path.dirname(now_pwd)
base_dir2=os.path.join(base_dir,'test')
#print(base_dir2)

def get_max_flod(file_name):
    aa=[]
    for i in os.listdir(file_name): 
                #print(i.find('-'))
                if i.find('-')>0:
                    #print([os.path.isfile(i) & i.find('-')>0])
                    aa.append(i)
    #print(aa)
    if aa==[]:
                    #print('2')
        os.mkdir(os.path.join(file_name,'1.0.0-20200928'))
    else:
        abc=[i[:i.find('-')] for i in aa]
        
        max_bbh=max(abc)
        
        max_ford=max_bbh[:len(max_bbh)-1]
        
        max_last=str(int(max_bbh[-1])+1)
        #print(int(max_bbh[-1]))
        #print(max_ford+max_last)
        new_file_name=max_ford+max_last+'-'+now_day 
        return new_file_name

def create_fold(file_name,version):
    
    os.mkdir(os.path.join(file_name,version))
    #print('新文件创建完成')
    return os.path.join(file_name,version)
# In[108]:



if __name__ == '__main__':
    try:
        parse=argparse.ArgumentParser(description='into para')
        defa=get_max_flod(file_name)
        parse.add_argument('--version',default=defa)
        args = parse.parse_args()
    #print(args)
        version=args.version
        file=create_fold(base_dir2,version)
        print('新文件创建完成:',file)

    except:
        print("无法创建文件夹")
    


# In[ ]:




